name: Build
on:
  push:
    branches:
      - main
      - workflow_test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get MXE
        run: 'git clone https://github.com/mxe/mxe.git'

      - name: Install dependencies for MXE
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake \
            autopoint \
            bash \
            bison \
            bzip2 \
            flex \
            g++ \
            g++-multilib \
            gettext \
            git \
            gperf \
            intltool \
            libc6-dev-i386 \
            libgdk-pixbuf2.0-dev \
            libltdl-dev \
            libgl-dev \
            libpcre3-dev \
            libssl-dev \
            libtool-bin \
            libxml-parser-perl \
            lzip \
            make \
            openssl \
            p7zip-full \
            patch \
            perl \
            python3 \
            python3-distutils \
            python3-mako \
            python3-pkg-resources \
            python-is-python3 \
            ruby \
            sed \
            unzip \
            wget \
            xz-utils

      - name: Build MXE
        run: 'cd mxe && make MXE_TARGETS=x86_64-w64-mingw32.static qtbase'

      
        

      # - name: Install Qt
      #   uses: jurplel/install-qt-action@v3
      #   with:
      #     version: '5.15.2'
      #     host: 'linux'
      #     target: 'desktop'
      #     arch: 'win64_msvc2019_64'
      #     cache: true

      - name: Run QMake
        run: |
          cd ./src
          mxe/usr/bin/x86_64-w64-mingw32.static-qmake-qt5 numpad-emulator.pro

      # - name: Show Content of Makefile
      #   run: 'cat ./src/Makefile'

      - name: Run CMake
        run: 'cd ./src && make'

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: numpad-emulator
          path: ${{ github.workspace }}/src/numpad-emulator.exe
